name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Pythonのバージョン確認
        run: python --version

      - name: calculatorの実行確認
        run: python -c "import calculator"